// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rxksuszhugltoxylxqmz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ4a3N1c3podWdsdG94eWx4cW16Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM2OTI3MDcsImV4cCI6MjA2OTI2ODcwN30.qFXNqF0nfI_Xx3oLVsf6DB3ZHLrKse_5tnF0hNhYdaI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});