// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vxjrmkhocaorhwzzumus.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ4anJta2hvY2Fvcmh3enp1bXVzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMwNTA4NDksImV4cCI6MjA2ODYyNjg0OX0.QUruY1vqclqAmd0a6mWqxK9dAonDuBxuaUOMUhIDVpE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});